heat_template_version: 2013-05-23

description: |
  This heat template will deploy a best practice installation of ready for Magento 1.8+

parameter_groups:

- label: Server Settings
  parameters:
  - web_flavor
  - db_flavor
  - web_server_count

parameters:
  prefix:
    label: Hostname Prefix
    description: The prefix to use for all server hostnames
    type: string
    default: magento
    constraints:
    - length:
        min: 1
        max: 12
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  web_flavor:
    label: Web Server Flavor
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.
    
  db_flavor:
    label: DB Server Flavor
    type: string
    default: 8 GB Performance
    constraints:
    - allowed_values:
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
    description: |
      Must be a valid Rackspace Cloud Server flavor for the region you have
      selected to deploy into.
  
  web_server_count:
    label: Number of Web Servers
    type: number
    default: 1
    constraints:
    - range:
        min: 0
        max: 7
    description: Must be between 0 and 7 servers.

  private_net_cidr:
    label: Private Network CIDR
    type: string
    default: 192.168.36.0/24
    description: CIDR to use for private network between nodes
    
  private_net_name:
    label: Private Network Name
    type: string
    default: DatabaseNetwork
    constraints:
    - length:
        min: 1
        max: 16
        
  db_image:
    label: Database Image
    type: string
    default: magento-db
    constraints:
    - allowed_values:
      - magento-db

resources:
  private_net:
    type: Rackspace::Cloud::Network
    properties:
      cidr: { get_param: private_net_cidr }
      label: { get_param: private_net_name }

  database_server:
    depends_on:
    - private_net
    type: Rackspace::Cloud::Server
    properties:
      name: 
        str_replace:
          template: prefix-db-01
          params:
            prefix: { get_param: prefix }
      flavor: { get_param: db_flavor }
      image: { get_param: db_image }
      config_drive: true
      networks:
      - uuid: "00000000-0000-0000-0000-000000000000"
      - uuid: "11111111-1111-1111-1111-111111111111"
      - network: { get_resource: private_net }
      metadata:
        group: magento-build
        rax-heat: { get_param: "OS::stack_id" }

  web_servers:
    depends_on:
    - private_net
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: web_server_count }
      resource_def:
        type: Rackspace::Cloud::Server
        properties:
          name:
            str_replace:
              template: prefix-web-%index%
              params:
                prefix: { get_param: prefix }
          flavor: { get_param: web_flavor }
          image: { get_param: web_image }
          config_drive: true
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - network: { get_resource: private_net }
          metadata:
            group: magento-build
            rax-heat: { get_param: "OS::stack_id" }

  load_balancer:
    type: Rackspace::Cloud::LoadBalancer
    depends_on:
    - web_servers
    properties:
      name: magento-lb
      nodes:
      - addresses: { get_attr: [web_servers, privateIPv4] }
        port: 8080
        condition: ENABLED
      healthMonitor:
        type: HTTP
        delay: 10
        timeout: 5
        attemptsBeforeDeactivation: 2
        path: /
        statusRegex: ^[23]0[0-2]$
      port: 80
      protocol: HTTP
      algorithm: LEAST_CONNECTIONS
      contentCaching: ENABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
